# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: sonukumar254585@gmail.com
author_name: sonucodes40
contract_name: saving_vault
preset_name: starter
project_name: OurVault

